name: Gatsby Publish

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node 18.13.0
        run: sudo npm cache clean -f && sudo npm install -g n && sudo n 18.13.0
      - name: Check Node Version
        run: /usr/local/bin/npm --version && node --version
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
